ignore:
  - "CouchTrackerCoreTests/**/*"
  - "CouchTrackerSyncTests/**/*"
  - "TMDBSwiftTestable/**/*"
  - "TMDBSwiftTests/**/*"
  - "TVDBSwiftTestable/**/*"
  - "TVDBSwiftTests/**/*"
  - "TraktSwiftTestable/**/*"
  - "TraktSwiftTests/**/*"
  - "CouchTrackerAppTestable/**/*"
