# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode10.1
language: objective-c
before_install:
  - bash setup.sh
script:
  - bundle exec pod install --repo-update
  - bash ci/travis.sh
after_success:
  - bash <(curl -s https://codecov.io/bash)
notifications:
  email: false
