version: 2

jobs:
  build-and-test:
    macos: # Specify the Xcode version to use
      xcode: "10.1.0"
    steps:
      - checkout
      - run:
          name: Setup build dependencies
          command: bash setup.sh
      - run:
          name: Build and run tests
          command: bundle exec fastlane lint
      # Collect XML test results data to show in the UI,
      # and save the same XML files under test-results folder
      # in the Artifacts tab
      - store_test_results:
          path: reports/
      - store_test_results:
          path: test_output/report.xml
      - store_artifacts:
          path: /tmp/test-results
          destination: scan-test-results
      - store_artifacts:
          path: ~/Library/Logs/scan
          destination: scan-logs

workflows:
  version: 2
  build-and-test:
    jobs:
      - build-and-test
