version: 2

defaults: &defaults
  macos:
    xcode: '10.1.0'
  parallelism: 1
  environment:
    LANG: en_US.UTF-8

jobs:
  build-and-test:
    steps:
      - checkout
      - restore_cache:
          key: 1-gems-{{ checksum "Gemfile.lock" }}
      - restore_cache:
          key: 1-pods-{{ checksum "Podfile.lock" }}
      - run:
          name: Setup build dependencies
          command: bash setup.sh
      - save_cache:
          key: 1-gems-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - save_cache:
          key: 1-pods-{{ checksum "Podfile.lock" }}
          paths:
            - Pods
      - run:
          name: Build and run tests
          command: bundle exec fastlane lint
      # Collect XML test results data to show in the UI,
      # and save the same XML files under test-results folder
      # in the Artifacts tab
      - store_test_results:
          path: reports/
      - store_test_results:
          path: test_output/report.xml
      - store_artifacts:
          path: /tmp/test-results
          destination: scan-test-results
      - store_artifacts:
          path: ~/Library/Logs/scan
          destination: scan-logs

workflows:
  version: 2
  build-and-test:
    jobs:
      - build-and-test
