version: 2

jobs:
  build-and-test:
    macos:
      xcode: '11.2.1'
    environment:
      LANG: en_US.UTF-8
    steps:
      - checkout
      - restore_cache:
          key: 1-gems-{{ checksum "Gemfile.lock" }}
      - restore_cache:
          key: 1-pods-{{ checksum "Podfile.lock" }}
      - run:
          name: Setup build dependencies
          command: bash setup.sh
      - save_cache:
          key: 1-gems-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - save_cache:
          key: 1-pods-{{ checksum "Podfile.lock" }}
          paths:
            - Pods
      - run:
          name: Build and run tests
          command: bundle exec fastlane lint
      - run:
          name: Codecov
          command: bash <(curl -s https://codecov.io/bash)
      # Collect XML test results data to show in the UI,
      # and save the same XML files under test-results folder
      # in the Artifacts tab
      - store_test_results:
          path: reports/
      - store_test_results:
          path: test_output/report.xml
      - store_artifacts:
          path: /tmp/test-results
          destination: scan-test-results
      - store_artifacts:
          path: ~/Library/Logs/scan
          destination: scan-logs
  beta-release:
    macos:
      xcode: '10.2.1'
    environment:
      LANG: en_US.UTF-8
    steps:
      - checkout
      - restore_cache:
          key: 1-gems-{{ checksum "Gemfile.lock" }}
      - restore_cache:
          key: 1-pods-{{ checksum "Podfile.lock" }}
      - run:
          name: Setup build dependencies
          command: bash setup.sh
      - save_cache:
          key: 1-gems-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - save_cache:
          key: 1-pods-{{ checksum "Podfile.lock" }}
          paths:
            - Pods
      - run:
          name: Release to Test Flight
          command: bundle exec fastlane beta

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build-and-test:
          filters:
            branches:
              ignore: master
      - beta-release:
          filters:
            branches:
              only: master
